# Generated by Django 2.0.9 on 2019-04-25 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('size', models.PositiveSmallIntegerField()),
                ('male', models.PositiveSmallIntegerField(default=0)),
                ('female', models.PositiveSmallIntegerField(default=0)),
                ('is_vip', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
