# Generated by Django 2.0.9 on 2019-05-27 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_enable_multi_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='cleared',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Cleared'),
            preserve_default=False,
        ),
    ]
