# Generated by Django 2.0.9 on 2019-05-27 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_table_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
