# Generated by Django 2.0.9 on 2019-05-31 17:03

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_update_in_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='state',
            field=django_fsm.FSMField(choices=[('b', 'Blank'), ('u', 'Using'), ('r', 'Reserved')], default='b', max_length=50, verbose_name='State'),
        ),
    ]
