# Generated by Django 2.0.9 on 2019-06-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_table_socket_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Online?'),
        ),
    ]
