# Generated by Django 2.0.9 on 2019-06-26 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_table_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='deposit',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Deposit'),
        ),
    ]
