# Generated by Django 2.0.9 on 2019-07-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ('user__first_name',), 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
    ]
