# Generated by Django 2.0.9 on 2019-07-15 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190713_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='socket_counter',
        ),
    ]
