# Generated by Django 2.0.9 on 2019-05-09 17:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('event_type', django_fsm.FSMField(choices=[('i', 'Image'), ('v', 'Video')], default='i', max_length=50)),
                ('file', models.ImageField(upload_to='events/%Y/%m/%d')),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('repeat', django_fsm.FSMField(choices=[('o', 'Only Once'), ('d', 'Every Day'), ('w', 'Every Week')], default='o', max_length=50)),
                ('at', models.TimeField()),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={})),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('at',),
            },
        ),
    ]
