# Generated by Django 2.0.9 on 2019-05-25 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('at',), 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterField(
            model_name='event',
            name='at',
            field=models.TimeField(verbose_name='event time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, verbose_name='details'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=django_fsm.FSMField(choices=[('i', 'Image'), ('v', 'Video')], default='i', max_length=50, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='event',
            name='file',
            field=models.ImageField(upload_to='events/%Y/%m/%d', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='event',
            name='from_date',
            field=models.DateField(null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='repeat',
            field=django_fsm.FSMField(choices=[('o', 'Only Once'), ('d', 'Every Day'), ('w', 'Every Week')], default='o', max_length=50, verbose_name='repeat'),
        ),
        migrations.AlterField(
            model_name='event',
            name='to_date',
            field=models.DateField(null=True, verbose_name='end date'),
        ),
    ]
