# Generated by Django 2.0.9 on 2019-05-12 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
