# Generated by Django 2.0.9 on 2019-05-31 14:36

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_enable_multi_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='file',
            field=sorl.thumbnail.fields.ImageField(upload_to='events/%Y/%m/%d', verbose_name='File'),
        ),
    ]
