# Generated by Django 2.0.9 on 2019-05-18 01:42

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Not available'), ('p', 'Downloading'), ('d', 'Uploading'), ('d', 'Ready')], default='d', max_length=50),
        ),
    ]
