# Generated by Django 2.0.9 on 2019-05-25 14:44

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('title',), 'verbose_name': 'Music', 'verbose_name_plural': 'Musics'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ('created',), 'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlist'},
        ),
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.CharField(max_length=32, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='music',
            name='external_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='music',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Not available'), ('p', 'Downloading'), ('d', 'Uploading'), ('d', 'Ready')], default='d', max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.URLField(verbose_name='Music url'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
    ]
