# Generated by Django 2.0.9 on 2019-05-27 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_enable_multi_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to='music.Music', verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='table',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='playlist', to='users.Table', verbose_name='Requester'),
        ),
    ]
