# Generated by Django 2.0.9 on 2019-06-15 00:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_update_in_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Details'),
        ),
        migrations.AddField(
            model_name='music',
            name='provider',
            field=django_fsm.FSMField(choices=[('t', 'Ting'), ('k', 'KuGou'), ('s', 'Spotify')], default='t', max_length=50, verbose_name='Music Provider'),
        ),
        migrations.AlterField(
            model_name='music',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Not available'), ('p', 'Downloading'), ('g', 'Uploading'), ('a', 'Ready')], default='d', max_length=50, verbose_name='State'),
        ),
    ]
