# Generated by Django 2.0.9 on 2019-07-02 10:31

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_music_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Requested'), ('a', 'Availiable')], default='d', max_length=50),
        ),
    ]
