# Generated by Django 2.0.9 on 2019-05-13 17:58

from __future__ import unicode_literals

from django.db import migrations
from cafe_backend.core.constants.types import CHAT_ROOM_TYPE


def create_default_channel(apps, schema_editor):
    Channel = apps.get_model('chat', 'Channel')
    User = apps.get_model('users', 'User')
    channel, created = Channel.objects.get_or_create(
        name='Public', channel_type=CHAT_ROOM_TYPE.public)

    count = 0
    for user in User.objects.all():
        channel.attendees.create(user=user)
        count += 1

    print("%d attendees created successfully." % count)


def reverse_func(apps, schema_editor):
    Channel = apps.get_model('chat', 'Channel')
    print(Channel.objects.all().delete())


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_channel, reverse_func)
    ]
