# Generated by Django 2.0.9 on 2019-05-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_attendees_for_existing_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('created',)},
        ),
    ]
