# Generated by Django 2.0.9 on 2019-05-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_channel_meta_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(default='', max_length=65536),
            preserve_default=False,
        ),
    ]
