# Generated by Django 2.0.9 on 2019-05-16 13:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_message_content'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('channel', 'user')},
        ),
    ]
