# Generated by Django 2.0.9 on 2019-05-25 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_unique_with_channel_n_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendee',
            options={'verbose_name': 'attendee', 'verbose_name_plural': 'attendees'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'ordering': ('created',), 'verbose_name': 'channel', 'verbose_name_plural': 'channels'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-modified',), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterField(
            model_name='attendee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_type',
            field=django_fsm.FSMField(choices=[('d', 'Direct'), ('c', 'Private'), ('p', 'Public')], default='c', max_length=50, verbose_name='channel type'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(max_length=256, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=32, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(max_length=65536, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='poster'),
        ),
    ]
