# Generated by Django 2.0.9 on 2019-04-28 00:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_create_category_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('name_zh', models.CharField(max_length=128, null=True)),
                ('name_ko', models.CharField(max_length=128, null=True)),
                ('description', models.TextField(max_length=1024)),
                ('description_zh', models.TextField(max_length=1024, null=True)),
                ('description_ko', models.TextField(max_length=1024, null=True)),
                ('price', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='dishes.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
