# Generated by Django 2.0.9 on 2019-05-25 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0006_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ('-modified',), 'verbose_name': 'dish', 'verbose_name_plural': 'dishes'},
        ),
        migrations.AlterModelOptions(
            name='dishimage',
            options={'ordering': ('-modified',), 'verbose_name': 'dish image', 'verbose_name_plural': 'dish images'},
        ),
        migrations.AlterModelOptions(
            name='dishreview',
            options={'ordering': ('-modified',), 'verbose_name': 'dish review', 'verbose_name_plural': 'dish reviews'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('-created',), 'verbose_name': 'price', 'verbose_name_plural': 'prices'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=128, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ko',
            field=models.CharField(max_length=128, verbose_name='korean name'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_en',
            field=models.TextField(max_length=1024, verbose_name='english description'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='description_ko',
            field=models.TextField(max_length=1024, verbose_name='korean description'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active?'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_en',
            field=models.CharField(max_length=128, verbose_name='english name'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='name_ko',
            field=models.CharField(max_length=128, verbose_name='korean name'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='comment',
            field=models.TextField(max_length=1024, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)], verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
    ]
