# Generated by Django 2.0.9 on 2019-05-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0007_add_language_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rate',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
