# Generated by Django 2.0.9 on 2019-05-27 14:56

from django.db import migrations
from django.db import models


def compute_dish_rates(apps, schema_editor):
    Dish = apps.get_model('dishes', 'Dish')
    count = 0

    for dish in Dish.objects.all():
        # dish.rate = dish.avg_rate
        if len(dish.reviews.all()) > 0:
            dish.rate = "%.2f" % dish.reviews.values('rate')\
                .aggregate(models.Avg('rate')).get('rate__avg', 0.0)
        else:
            dish.rate = 0.0
        dish.save()
        count += 1

    print("%d dishes were updated successfully." % count)


def reverse_func(apps, schema_editor):
    Dish = apps.get_model('dishes', 'Dish')
    count = 0

    for dish in Dish.objects.all():
        dish.rate = 0.0
        dish.save()
        count += 1

    print("%d dishes were updated successfully." % count)


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0008_dish_rate'),
    ]

    operations = [
        migrations.RunPython(compute_dish_rates, reverse_func)
    ]
