# Generated by Django 2.0.9 on 2019-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0009_compute_dish_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None, max_length=40, null=True, verbose_name='Slug'),
        ),
    ]
