# Generated by Django 2.0.9 on 2019-05-27 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0011_create_default_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dishes', to='dishes.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dishimage',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dishes.Dish', verbose_name='Dish'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='dishes.Dish', verbose_name='Dish'),
        ),
        migrations.AlterField(
            model_name='dishreview',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Table', verbose_name='Table'),
        ),
        migrations.AlterField(
            model_name='price',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='dishes.Dish', verbose_name='Dish'),
        ),
    ]
