# Generated by Django 2.0.9 on 2019-05-31 10:22

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0012_update_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishimage',
            name='file',
            field=sorl.thumbnail.fields.ImageField(upload_to='dishes/%Y/%m/%d', verbose_name='Image File'),
        ),
    ]
