# Generated by Django 2.0.9 on 2019-05-29 03:50

from django.db import migrations


def update_original_images_with_ratio(apps, schema_editor):
    DishImage = apps.get_model('dishes', 'DishImage')
    DishImage.objects.filter(small='').delete()


def reverse_func(*args, **kargs):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0013_dish_image_ratio'),
    ]

    operations = [
        migrations.RunPython(update_original_images_with_ratio, reverse_func)
    ]
