# Generated by Django 2.0.9 on 2019-07-12 20:01

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0014_dish_rate_made_not_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='position',
            field=django_fsm.FSMField(choices=[('c', 'Rest Counter'), ('n', 'Kitchen')], default='n', max_length=50, verbose_name='Dish Position'),
        ),
    ]
