# Generated by Django 2.0.9 on 2019-07-12 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ('-created',), 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
    ]
