# Generated by Django 2.0.9 on 2019-05-03 16:39

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('booking_type', django_fsm.FSMField(choices=[('c', 'Contact'), ('d', 'dish'), ('e', 'exchange'), ('m', 'merge')], default='c', max_length=50)),
                ('state', django_fsm.FSMField(choices=[('d', 'Requested'), ('a', 'Approved'), ('r', 'Rejected')], default='d', max_length=50)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_bookings', to='users.Table')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_bookings', to='users.Table')),
            ],
            options={
                'ordering': ('-modified',),
            },
        ),
        migrations.CreateModel(
            name='BookingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField(max_length=65536)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.Booking')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Table')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
