# Generated by Django 2.0.9 on 2019-05-25 15:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190508_1159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-modified',), 'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='bookingmessage',
            options={'ordering': ('-modified',), 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_type',
            field=django_fsm.FSMField(choices=[('c', 'Contact'), ('d', 'Dish'), ('e', 'Exchange'), ('m', 'Merge')], default='c', max_length=50, verbose_name='Booking Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Details'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_bookings', to='users.Table', verbose_name='Receiver'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='requester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_bookings', to='users.Table', verbose_name='Requester'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Requested'), ('a', 'Approved'), ('r', 'Rejected'), ('c', 'Canceled'), ('x', 'Archived')], default='d', max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='content',
            field=models.TextField(max_length=65536, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='bookingmessage',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Table', verbose_name='Poster'),
        ),
    ]
