# Generated by Django 2.0.9 on 2019-05-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_enable_multi_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmessage',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bookings.Booking', verbose_name='Booking'),
        ),
    ]
