# Generated by Django 2.0.9 on 2019-05-08 02:23

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_is_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_complete',
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Requested'), ('c', 'Canceled'), ('e', 'Delivered'), ('x', 'Archived')], default='d', max_length=50),
        ),
    ]
