# Generated by Django 2.0.9 on 2019-05-24 12:30

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_fsm_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_canceled',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Requested'), ('c', 'Canceled'), ('e', 'Delivered'), ('x', 'Archived')], default='d', max_length=50),
        ),
    ]
