# Generated by Django 2.0.9 on 2019-05-25 14:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_item_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ('-created',), 'verbose_name': 'order item', 'verbose_name_plural': 'order items'},
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Requested'), ('c', 'Canceled'), ('e', 'Delivered'), ('x', 'Archived')], default='d', max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_rate',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Discount rate'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Requested'), ('c', 'Canceled'), ('e', 'Delivered'), ('x', 'Archived')], default='d', max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='to_table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_order_items', to='users.Table', verbose_name='Target table'),
        ),
    ]
