# Generated by Django 2.0.9 on 2019-05-31 07:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_update_in_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'customers': {'female': 0, 'male': 1}}, verbose_name='Details'),
        ),
    ]
