# Generated by Django 2.0.9 on 2019-05-31 22:47

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Requested'), ('e', 'Delivered'), ('x', 'Archived')], default='d', max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='state',
            field=django_fsm.FSMField(choices=[('d', 'Requested'), ('c', 'Canceled'), ('e', 'Delivered')], default='d', max_length=50, verbose_name='State'),
        ),
    ]
