# Generated by Django 2.0.9 on 2019-06-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_is_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Free?'),
        ),
    ]
