# Generated by Django 2.0.9 on 2019-07-02 02:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderitem_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Checkout Time'),
        ),
        migrations.AddField(
            model_name='order',
            name='income',
            field=models.FloatField(default=0.0, verbose_name='Income'),
        ),
        migrations.AddField(
            model_name='order',
            name='wipe_zero',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Wipe Zero'),
        ),
    ]
