# Generated by Django 2.0.9 on 2019-05-08 04:15

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='type',
            field=django_fsm.FSMField(choices=[('i', 'Image'), ('v', 'Video')], default='i', max_length=50),
        ),
    ]
