# Generated by Django 2.0.9 on 2019-05-25 04:26

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ('-modified',), 'verbose_name': 'advertisement', 'verbose_name_plural': 'advertisements'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='file',
            field=models.ImageField(upload_to='ads/%Y/%m/%d', verbose_name='ads_file'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=django_fsm.FSMField(choices=[('i', 'Image'), ('v', 'Video')], default='i', max_length=50, verbose_name='ads_type'),
        ),
    ]
