# Generated by Django 2.0.9 on 2019-05-31 14:24

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_add_language_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='file',
            field=sorl.thumbnail.fields.ImageField(upload_to='ads/%Y/%m/%d', verbose_name='File'),
        ),
    ]
