# Generated by Django 2.0.9 on 2019-06-05 15:22

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0014_dish_rate_made_not_required'),
        ('advertisements', '0004_thumbnail_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='dish',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='广告', to='dishes.Dish'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='type',
            field=django_fsm.FSMField(choices=[('i', 'Internal'), ('e', 'External')], default='e', max_length=50, verbose_name='Type'),
        ),
    ]
